# This config contains the parameters required for running the FullSim CMSSW chain on Condor
# See model_params_demo.yaml for examples and descriptions

work_space: /afs/cern.ch/work/e/ebhal/Semi_visible_jets_Condor_v3
lhe_file_path: /afs/cern.ch/work/e/ebhal/public/DMsimp_SVJ_s_spin1_splitLHE
# Model name will be unecessary once complete chain is ready
#model_name: DMsimp_SVJ_s_spin1
n_events: 100
n_jobs: 500
alpha_d: 0.23
process_type: "s-channel"
m_med: 2500
m_d: 20
n_f: 1
r_inv: 0.3
model_name: DMsimp_SVJ_s_spin1_mZp-2500_mDQ-20
total_events: 50000
x_sec: 2.364
