# This config contains the parameters required for running the FullSim CMSSW chain on Condor
# See model_params_demo.yaml for examples and descriptions

work_space: /afs/cern.ch/work/e/ebhal/Semi_visible_jets_Condor_v4
lhe_file_path: /afs/cern.ch/work/e/ebhal/public/DMsimp_SVJ_t_splitLHE
n_events: 100
n_jobs: 500
alpha_d: 0.23
process_type: "t-channel"
m_med: 2000
m_d: 100
n_f: 1
r_inv: 0.3
x_sec: 97.0

model_name: DMsimp_SVJ_t_mPhi-2000_mDQ-100
total_events: 50000
