work_space: /afs/cern.ch/work/e/ebhal/SVJ_Condor
lhe_file_path: /afs/cern.ch/work/e/ebhal/public/SVJ_s_splitLHE
n_events: 100
n_jobs: 500
year: 2018
alpha_d: peak
process_type: "s-channel"
m_med: 3000
m_d: 10
n_f: 2
r_inv: 0.3

model_name: SVJ_s_2018_mZp-3000_mDQ-10_rinv-0p3_aD-peak
total_events: 50000
x_sec_mg: 0.1293
