# This config contains the parameters required for running the FullSim CMSSW chain on Condor
# The key names cannot be changed
# Paths can be given as local or absolute and strings are not required to be enclosed in quotes

# Directory to deposit CMSSW releases and output root files from FullSim. Specify somewhere with a lot of space as output may be large
work_space: /afs/cern.ch/work/e/ebhal/Semi_visible_jets_Condor_NewWorkflow

# Directory to store LHE files created by MadGraph, and access them for FullSim running
lhe_file_path: /afs/cern.ch/work/e/ebhal/public/DMsimp_SVJ_s_spin1_splitLHE

# Number of events per job (FullSim)
n_events: 100

# Number of jobs to run (FullSim)
n_jobs: 500

# Running dark coupling at 1 TeV. A numerical value can be specified, as well the strings 'low', 'peak' and 'high'
alpha_d: 0.23

# Process type (s-channel or t-channel)
process_type: "s-channel"

# Mass of mediator (Z' for s-channel, Phi for t-channel) in GeV
m_med: 1000

# Mass of dark quarks in GeV
m_d: 10

# Number of dark hadron flavours. n_f = 2 recommended by theorists
n_f: 2

# Fraction of final state particles that are stable and invisible
r_inv: 0.3
#----------------------------------------------------------------

# The following parameters are written by various scripts as they are not set by the user

# Descriptive identifier for model. Written in submitGridpackGeneration.py. MAYBE ADD ALPHA_D TO THIS
model_name: DMsimp_SVJ_s_spin1_mZp-1000_mDQ-10_rinv-0p3

# total_events written in submitGridpackGeneration.py
total_events: 50000

# Cross section (pb) specified by MadGraph. Written in runLHERetrieval.py
x_sec: 81.3
