work_space: /afs/cern.ch/work/e/ebhal/SVJ_Condor
lhe_file_path: /afs/cern.ch/work/e/ebhal/public/SVJ_t_splitLHE
n_events: 100
n_jobs: 500
year: 2017
alpha_d: peak
process_type: "t-channel"
m_med: 1000
m_d: 10
n_f: 2
r_inv: 0.3

model_name: SVJ_t_2017_mPhi-1000_mDQ-10_rinv-0p3_aD-peak
total_events: 50000
x_sec_mg: 95.5
