# This config contains the parameters required for running the FullSim CMSSW chain on Condor
# See model_params_demo.yaml for examples and descriptions
work_space: /afs/cern.ch/work/e/ebhal/SVJ_Condor_v6
lhe_file_path: /afs/cern.ch/work/e/ebhal/public/SVJ_s_splitLHE_v6
n_events: 100
n_jobs: 500
year: 2017
alpha_d: peak
process_type: "s-channel"
m_med: 3000
m_d: 10
n_f: 2
r_inv: 0.3

